services:

    ctrl_rad.menu_builder:
        class: Ctrl\RadBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    ctrl_rad.menu.sidebar:
        class: Knp\Menu\MenuItem
        factory: [ "@ctrl_rad.menu_builder", createSidebarMenu ]
        arguments: ["@request_stack", "@event_dispatcher"]
        tags:
            - { name: knp_menu.menu, alias: sidebar }

    ctrl_rad.menu_configurator.sidebar:
        class: Ctrl\RadBundle\Menu\SidebarMenuBuilder
        arguments: [ "@security.authorization_checker" ]
        tags:
            - { name: kernel.event_listener, event: ctrl_rad.menu_configure, method: onMenuConfigure }
