services:

    ctrl_rad.menu.sidebar:
        class: Ctrl\RadBundle\Menu\SidebarMenuBuilder
        tags:
            - { name: kernel.event_listener, event: ctrl_rad.menu_configure, method: onMenuConfigure }