services:

    #
    # Twig extensions
    #
#
#    twig.extension.text:
#        class: Twig_Extensions_Extension_Text
#        tags:
#            - { name: twig.extension }

    twig.extension.bootstrap:
        class: Ctrl\RadBundle\Twig\BootstrapExtension
        arguments: [@request_stack, @router, @translator.default]
        public: false
        tags:
            - { name: twig.extension }