services:

    #
    # entity services
    #

    ctrl_rad.entity.user:
        class: Ctrl\RadBundle\EntityService\UserService
        tags:
            - { name: ctrl_rad.entity_service }

    #
    # Twig extensions
    #

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.ctrl_rad:
        class: Ctrl\RadBundle\Twig\CtrlRadExtension
        arguments: [@twig, %ctrl_rad.config%]
        public: false
        tags:
            - { name: twig.extension }

    twig.extension.bootstrap:
        class: Ctrl\RadBundle\Twig\BootstrapExtension
        arguments: [@request_stack, @router, @translator.default]
        public: false
        tags:
            - { name: twig.extension }